name: "Phpstan"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  phpstan81:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@v1
    with:
      php: "8.1"


  phpstan80:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@v1
    with:
      php: "8.0"

  lower:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/phpstan.yml@v1
    with:
      php: "7.2"
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
